### PR TITLE
upload a single packed workflow to a release

### PR DESCRIPTION
**Pull request by johnbradley**
Changes the packed workflow release process. After this change 
a release will be specific to a single workflow. That workflow will
be packed and uploaded to the release.
There are two methods a user can use to pack and release a workflow:
- Add a tag ending in '-v<number' to a commit and push to github
- Create a github release with tag version ending in '-v<number'

The part of the tag before the '-v<number>' part is assumed to
be the name of a workflow within the `workflows` directory.
This workflow will be packed and added to the release by 
`pack_and_release_workflow.py` running under circleci.
If the release doesn't exist a release will be created.

Adds PyGithub to the requirements to manage github
releases.

I tested these changes in another repo.

Part of #62

### CODE REVIEW

**Comment by dleehr** [comment]
Nice work, this is very welcome. Two questions:

1. How does this fit in with a bespin WorkflowVersion? e.g. if I want to release a new version of a workflow, do I start here (in bespin-cwl) or there (in bespin-api)?
2. Can you document (or provide a shell script) with the specific command to tag and release a workflow? That's something we'd want to do consistently, and I'm not entirely clear on what I should do to cause this to happen. It looks like the new python script has some safeguards (checking that the named workflow exists) that would be useful to run before creating and pushing the tag.

**Comment by johnbradley** [comment]
>How does this fit in with a bespin WorkflowVersion? e.g. if I want to release a new version of a workflow, do I start here (in bespin-cwl) or there (in bespin-api)?

My thought was you would start here (in bespin-cwl). You make your changes and commit them. Then you figure out what the new version version. Tag the branch and push the tags.
For example:
Pretend we previously released `exomeseq-gatk4-preprocessing-v2`.
So the next version of this would be `v3`.
Tag the appropriate branch and push to github:
```
git tag -a exomeseq-gatk4-preprocessing-v3 -m 'Create exomeseq-gatk4-preprocessing V3'
git push --tags
```
Then we import the workflow version via bespin cli:
```
bespin workflow-version create --workflow exomeseq-gatk4-preprocessing \
  --url https://github.com/Duke-GCB/bespin-cwl/releases/download/exomeseq-gatk4-preprocessing-v3/exomeseq-gatk4-preprocessing.cwl  \
  --description 'Added turbo boosters'
  --version 3
```

A script to release a particular workflow file would be convenient.
If we are going to run a script locally we could also just cut circleci out of the equation.

**Comment by johnbradley** [comment]
I added a script `scripts/release-workflow.sh` and some notes on how to run it in a new README.
Since we already have released workflows we will need to create some tags that correspond to the versions of previously released bespin workflows.

**Comment by dleehr** [comment]
Think we should close this after our meetings about versioning this week?

**Comment by johnbradley** [comment]
> Think we should close this after our meetings about versioning this week?
Yep. Closing.

**Pull request closed without merging**
