### PR TITLE
Raise memory in mapping step to fix out-of-memory errors

### PR DESCRIPTION
**Pull request by dleehr**
Raises RAM requirement in mapping step to 24G

### CODE REVIEW

**Comment by dleehr** [comment]
Note that this will not merge back into master, it's a hot fix on v0.9.2 tag (5227b504f359561baed8c4fd7efea5549c182bad) to a branch from that release.

Also note that v0.9.2 was released while we were still using Travis-CI (not Circle), so the Circle build checks fail

**Comment by johnbradley** [comment]
Do we also need to raise the sort step ramMin to 24000 as well?
SortSam failed until that change was put in place.

**Comment by dleehr** [comment]
Good catch. I actually couldn't find the overrides file I used before 😢

**Comment by dleehr** [comment]
I found the original file I used (in the github repo for my vacation handover) but it doesn't mention SortSam. Looks like you configured that on Feb 13 based on an email I have:

> Yesterday at 9AM, John restarted the job with an increased allocation on the SortSam step too. So he’ll continue to monitor that. If you have any guidance on memory limits for other steps (especially for bigger jobs like this), that might help us prevent further delay.

So, the sort step with `ramMin: 4000` failed but worked at `ramMin: 24000`? Was there any other increment tried? Obviously we want a number that will work but I'm curious where the 24000 came from.

**Comment by johnbradley** [comment]
> So, the sort step with ramMin: 4000 failed but worked at ramMin: 24000? 

Yes

> Was there any other increment tried? Obviously we want a number that will work but I'm curious where the 24000 came from.

I just copied the value we raised the previous step to. No other values were tried.

**Comment by dleehr** [comment]
I see. I'm going to try 6000, since I recognize we need to raise it, but suspect that 24000 is overkill. Picard is a java tool and our picard-SortSam.cwl limits the heap size to 4g:

https://github.com/Duke-GCB/bespin-cwl/blob/5227b504f359561baed8c4fd7efea5549c182bad/tools/picard-SortSam.cwl#L45

So, assuming you didn't change that, it looks like SortSam worked with a 4g heap, and maybe we just need a little bit of overhead.

**Pull request merged**
